### ISSUE TITLE
Playlist Card Component

### ISSUE THREAD

**Issue by SheltonRolleFS** [SheltonRolleFS/AnimePlaylist#17]
I need to create the playlist card component that will be used to showcase playlists in a list to the user. This component needs the following pieces of information about the playlist:

- Playlist Thumbnail
- Playlist Name
- Playlist Genre
- Number of Likes
- Action buttons
  - Share
  - Edit
  - Delete

### Tasks
- [x] Create the component with all its dynamic data variables
- [x] Format the layout to match the wireframe
- [x] Style where needed to get a rough idea of the layout ( This should not be fully styling the component, just put flex / grid positioning on whatever might need it so I know how the features of the card will flow )

**Comment by SheltonRolleFS** [comment]
# Update - Sun [ Feb. 6, 2022 ] @ 12:57AM
I had finished 2 of the 3 tasks above quite a while ago but I guess I forgot to mark them as done. As for the final styling, that will come way later in development since right now I'm more focused on getting the functionality of the application done. For now though, this issue is completed.
